# Generated by Django 4.0 on 2023-08-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_executor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Өнім', 'verbose_name_plural': 'Өнімдер'},
        ),
    ]
