# Generated by Django 4.2 on 2023-09-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=200)),
                ('personName', models.CharField(max_length=200)),
                ('goalsAndTasks', models.TextField()),
                ('dataCollection', models.TextField()),
                ('dataFilteringAndAnalysis', models.TextField()),
                ('dataStorage', models.TextField()),
                ('url', models.URLField()),
                ('clickjacking', models.BooleanField(default=False)),
                ('csrf', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, null=True)),
                ('open_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('sql_injection', models.BooleanField(default=False)),
                ('xss', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'OSINTs',
                'ordering': ['organizationName'],
            },
        ),
    ]
