# Generated by Django 4.2 on 2023-10-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('osint', '0002_alter_osint_datacollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osint',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Osint', to='project.project'),
        ),
    ]
