# Generated by Django 4.2 on 2023-10-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pentesting', '0001_initial'),
        ('ISSAF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilityassessment',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VulnerabilityAssessment', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='usertrainingandawareness',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserTrainingAndAwareness', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='threatassessment',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ThreatAssessment', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='securitypolicyassessment',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecurityPolicyAssessment', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='physicalsecurityassessment',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PhysicalSecurityAssessment', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='networksecurityaudit',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NetworkSecurityAudit', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='monitoringincidentdetectionassessment',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MonitoringIncidentDetectionAssessment', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='incidentrecoveryandcontinuity',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IncidentRecoveryAndContinuity', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='dataprotectionandsecuritymonitoring',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DataProtectionAndSecurityMonitoring', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='complianceassessment',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ComplianceAssessment', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='authenticationauthorizationassessment',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuthenticationAuthorizationAssessment', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='assetidentification',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AssetIdentification', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='accesscontrolassessment',
            name='pentest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccessControlAssessment', to='pentesting.pentest'),
        ),
    ]
