# Generated by Django 4.2 on 2023-10-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pentesting', '0001_initial'),
        ('OWASP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xxeviolation',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_XXEViolation', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='xssattack',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_XSSAttack', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='sensitivedataexposure',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_SensitiveDataExposure', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='securitymisconfiguration',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_SecurityMisconfiguration', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='securitylogging',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_SecurityLogging', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='knownvulnerabilities',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_KnownVulnerabilities', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='insecuredeserializationattack',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_InsecureDeserializationAttack', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='injection',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_injection', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='authenticationviolation',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_AuthenticationViolation', to='pentesting.pentest'),
        ),
        migrations.AddField(
            model_name='accesscontrolviolation',
            name='pentest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWASP_AccessControlViolation', to='pentesting.pentest'),
        ),
    ]
