# Generated by Django 4.2 on 2023-10-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pentesting', '0003_pentest_osint'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_search', models.TextField(blank=True, null=True)),
                ('exploitation_attempts', models.TextField(blank=True, null=True)),
                ('system_reaction_evaluation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VulnerabilityAnalysis', to='pentesting.pentest')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsAnalysisAndReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_processing', models.TextField(blank=True, null=True)),
                ('risk_assessment', models.TextField(blank=True, null=True)),
                ('detailed_audit_report_with_recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ResultsAnalysisAndReporting', to='pentesting.pentest')),
            ],
        ),
        migrations.CreateModel(
            name='InformationGathering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_search_and_scanning', models.TextField(blank=True, null=True)),
                ('port_and_service_analysis', models.TextField(blank=True, null=True)),
                ('publicly_available_documentation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InformationGathering', to='pentesting.pentest')),
            ],
        ),
        migrations.CreateModel(
            name='DataAnalysisAndDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_steps_record', models.TextField(blank=True, null=True)),
                ('issue_description_and_remediation_recommendations', models.TextField(blank=True, null=True)),
                ('audit_report', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DataAnalysisAndDocumentation', to='pentesting.pentest')),
            ],
        ),
        migrations.CreateModel(
            name='AuditPreparationAndPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_objectives_and_scope', models.TextField(blank=True, null=True)),
                ('audit_plan', models.TextField(blank=True, null=True)),
                ('audit_team_and_roles', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuditPreparationAndPlanning', to='pentesting.pentest')),
            ],
        ),
        migrations.CreateModel(
            name='AuditInitiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_objectives', models.TextField(blank=True, null=True)),
                ('methodology_and_tools', models.TextField(blank=True, null=True)),
                ('audit_schedule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuditInitiation', to='pentesting.pentest')),
            ],
        ),
        migrations.CreateModel(
            name='AuditExecutionAndTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penetration_testing', models.TextField(blank=True, null=True)),
                ('vulnerability_data_collection_and_analysis', models.TextField(blank=True, null=True)),
                ('security_policy_testing', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuditExecutionAndTesting', to='pentesting.pentest')),
            ],
        ),
        migrations.CreateModel(
            name='AuditCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_meeting', models.TextField(blank=True, null=True)),
                ('audit_report_delivery', models.TextField(blank=True, null=True)),
                ('project_closure', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuditCompletion', to='pentesting.pentest')),
            ],
        ),
        migrations.CreateModel(
            name='AccessMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_maintenance_mechanisms', models.TextField(blank=True, null=True)),
                ('attacker_activity_masking', models.TextField(blank=True, null=True)),
                ('activity_monitoring_and_access_to_resources', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pentest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccessMaintenance', to='pentesting.pentest')),
            ],
        ),
    ]
